// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCShGskzmICHIg0UV99QWBIjgooFtXeiMI',
    appId: '1:766301000676:web:28cfa6712e069723f8edf1',
    messagingSenderId: '766301000676',
    projectId: 'al-wershah',
    authDomain: 'al-wershah.firebaseapp.com',
    storageBucket: 'al-wershah.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv61vm0R5IfwZY9-gsSs3Yx0YSd_5IIbo',
    appId: '1:766301000676:android:b55f2fb6480624c2f8edf1',
    messagingSenderId: '766301000676',
    projectId: 'al-wershah',
    storageBucket: 'al-wershah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv61vm0R5IfwZY9-gsSs3Yx0YSd_5IIbo',
    appId: '1:766301000676:ios:b55f2fb6480624c2f8edf1',
    messagingSenderId: '766301000676',
    projectId: 'al-wershah',
    storageBucket: 'al-wershah.firebasestorage.app',
    iosBundleId: 'com.elwarsha.elWarsha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv61vm0R5IfwZY9-gsSs3Yx0YSd_5IIbo',
    appId: '1:766301000676:ios:b55f2fb6480624c2f8edf1',
    messagingSenderId: '766301000676',
    projectId: 'al-wershah',
    storageBucket: 'al-wershah.firebasestorage.app',
    iosBundleId: 'com.elwarsha.elWarsha',
  );
}